//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by zncad.rc
//
#define IDD_DTOPTION                    9
#define IDS_PROJNAME                    100
#define IDS_BFF_TITLE                   101
#define IDS_BUTTON_DWGTOGRID            102
#define IDS_BUTTON_APPLYTODWG           103
#define IDS_BUTTON_TOXLS                104
#define IDS_BUTTON_FROMXLS              105
#define IDD_MOD_ENT                     140
#define IDB_CHECKMARK                   141
#define IDB_DUNDASLOGO                  142
#define IDD_XHLCABLEINFO                143
#define IDD_ZNCADOPTION                 145
#define IDD_CABLEINFO                   146
#define IDD_DISTTOXHL                   147
#define IDD_DLPX                        151
#define IDD_DTCABLEINFO                 152
#define IDD_DTMAINCABLEINFO             154
#define IDD_ADDBOX                      155
#define IDC_LIST_GRID                   201
#define IDC_RADIO_PMTRB_XHJ             202
#define IDC_RADIO_PMTRB_DC              203
#define IDC_RADIO_PMTRB_JYJ             204
#define IDC_RADIO_PMTRB_JCB             205
#define IDC_EDIT_PMTRB_XHJ_BLKNAME      206
#define IDC_BUTTON_PMTRB_XHJ_SEL        207
#define IDC_RADIO_PMTRB_JYJ1            208
#define IDC_RADIO_PMTRB_JY2             209
#define IDC_RADIO_PMTRB_JYJ3            210
#define IDC_RADIO_PMTRB_JYJ4            211
#define IDC_EDIT_CABLEINFO_ALL          212
#define IDC_EDIT_CABLEINFO_LEN          213
#define IDC_EDIT_CABLEINFO_DIST1        214
#define IDC_EDIT_CABLEINFO_DIST2        215
#define IDC_EDIT_CABLEINFO_GDNUM        216
#define IDC_EDIT_CABLEINFO_BOXNUM       217
#define IDC_EDIT_CABLEINFO_PLUS         218
#define IDC_EDIT_CABLEINFO_BOXFNUM      219
#define IDC_EDIT_CABLEINFO_INTOXHL      220
#define IDC_EDIT_CABLEINFO_TYPE         221
#define IDC_EDIT_CABLEINFO_BACKUP       222
#define IDC_EDIT_CABLEINFO_COEFFICIENT  223
#define IDC_EDIT_CABLEINFO_PERINTOXHL   224
#define IDC_EDIT_CABLEINFO_PERGD        225
#define IDC_EDIT_CABLEINFO_PERBETWEENGD 226
#define IDC_EDIT_CABLEINFO_PERBOX       227
#define IDC_EDIT_CABLEINFO_PERBOXF      228
#define IDC_EDIT_CABLEINFO_SN           229
#define IDC_EDIT_CABLEINFO_INTOXHLNAME  230
#define IDC_EDIT_CABLEINFO_OLD          231
#define IDC_EDIT_CABLEINFO_PERBETWEENBOXF 232
#define IDC_EDIT_CABLEINFO_LENFORPLUS   233
#define IDC_EDIT_XHLCABLE_INTOXHL       234
#define IDC_EDIT_XHLCABLE_CROSSGD       235
#define IDC_EDIT_XHLCABLE_PERGD         236
#define IDC_EDIT_XHLCABLE_BETWEENGD     237
#define IDC_EDIT_ZNOPTION_CABLE_COEFFICIENT 238
#define IDC_EDIT_ZNOPTION_CABLE_PERINTOXHL 239
#define IDC_EDIT_ZNOPTION_CABLE_PERGD   240
#define IDC_EDIT_ZNOPTION_CABLE_PERBETWEENGD 241
#define IDC_EDIT_ZNOPTION_CABLE_PERBOX  242
#define IDC_EDIT_ZNOPTION_CABLE_PERBOXF 243
#define IDC_EDIT_ZNOPTION_CABLE_PERBETWEENBOXF 244
#define IDC_EDIT_DTOPTION_SXJPER        244
#define IDC_EDIT_ZNOPTION_TOL_CHECKGD   245
#define IDC_RADIO_ZNOPTION_4LINE        246
#define IDC_RADIO_ZNOPTION_2LINE        247
#define IDC_RADIO_ZNOPTION_DS2          248
#define IDC_RADIO_ZNOPTION_DS3          249
#define IDC_RADIO_ZNOPTION_QK2          250
#define IDC_RADIO_ZNOPTION_QK4          251
#define IDC_RADIO_ZNOPTION_DCDS0        252
#define IDC_RADIO_ZNOPTION_DCDS2        253
#define IDC_RADIO_ZNOPTION_DCDS3        254
#define IDC_CHECK_ZNOPTION_XHJWITHJYJ   255
#define IDC_EDIT_ZNOPTION_TOL_CHECKJYJXHJ 256
#define IDC_EDIT_ZNOPTION_TOL_CHECKJYJXHJOVERLAP 257
#define IDC_EDIT2                       258
#define IDC_DEVICE_RADIO1               263
#define IDC_DEVICE_RADIO2               264
#define IDC_DEVICE_RADIO3               265
#define IDC_DEVICE_RADIO4               266
#define IDC_DEVICE_RADIO5               267
#define IDC_DEVICE_RADIO6               268
#define IDC_DEVICE_RADIO7               269
#define IDC_DEVICE_RADIO8               270
#define IDC_COLOR_RADIO9                271
#define IDC_COLOR_RADIO10               272
#define IDC_COLOR_RADIO11               273
#define IDC_COLOR_RADIO12               274
#define IDC_COLOR_RADIO13               275
#define IDC_COLOR_RADIO14               276
#define IDC_COLOR_RADIO15               277
#define IDC_COLOR_RADIO16               278
#define IDC_BUTTON1                     279
#define IDC_BUTTON2                     280
#define IDC_EDIT_DTOPTION_WQRATIO       281
#define IDC_EDIT_DTOPTION_ZT            282
#define IDC_EDIT_DTOPTION_GUOGUIPER     283
#define IDC_EDIT_DTOPTION_DISTJIEXU     284
#define IDC_EDIT_DTOPTION_RFMPER        285
#define IDC_EDIT_DTOPTION_AZYULIANG     286
#define IDC_STATIC8                     287
#define IDC_RADIO1                      288
#define IDC_RADIO2                      289
#define IDC_EDIT1                       290
#define IDC_RADIO3                      291
#define IDC_RADIO4                      292
#define IDC_RADIO5                      293
#define IDC_RADIO6                      294
#define IDC_RADIO7                      295
#define IDC_RADIO8                      296
#define IDC_RADIO9                      297
#define IDC_RADIO10                     298
#define IDC_RADIO11                     299
#define IDC_RADIO12                     300
#define IDC_EDIT_DTCABLEINFO_ALL        301
#define IDC_EDIT_DTCABLEINFO_LENFORPLUS 302
#define IDC_EDIT_DTCABLEINFO_DIST1      303
#define IDC_EDIT_DTCABLEINFO_DIST2      304
#define DC_EDIT_DTCABLEINFO_DIST1       304
#define IDC_EDIT_DTCABLEINFO_ZT         305
#define IDC_EDIT_DTCABLEINFO_TOCABLE    306
#define IDC_EDIT_DTCABLEINFO_GD         307
#define IDC_EDIT_DTCABLEINFO_CDLIAN     308
#define IDC_EDIT_DTCABLEINFO_SX         309
#define IDC_EDIT_DTCABLEINFO_RFM        310
#define IDC_EDIT_DTCABLEINFO_ANZHU      311
#define IDC_EDIT_DTCABLEINFO_XIUZ       312
#define IDC_EDIT_DTCABLEINFO_LEN1       313
#define IDC_EDIT_DTCABLEINFO_CABLENAME  314
#define IDC_EDIT_DTCABLEINFO_BACKXINSHU 315
#define IDC_EDIT_DTCABLEINFO_CABLETYPE  316
#define IDC_EDIT_DTCABLEINFO_CABLENUM   317
#define IDC_EDIT_DTCABLEINFO_OLD        318
#define IDC_EDIT_DTCABLEINFO_LEN        319
#define IDC_EDIT_DTCABLEINFO_WANQU1     320
#define IDC_EDIT_DTCABLEINFO_LEN2       321
#define IDC_EDIT_DTCABLEINFO_LEN3       322
#define IDC_EDIT_DTCABLEINFO_WANQU2     323
#define IDC_EDIT_DTCABLEINFO_DISTCABLE  324
#define IDC_EDIT_DTCABLEINFO_DISTJIEXU  324
#define IDC_EDIT_DTCABLEINFO_ZUOTOU     325
#define IDC_EDIT_DTCABLEINFO_ANZHUANG   326
#define IDC_EDIT_DTCABLEINFO_GUOGUI     327
#define IDC_EDIT_DTCABLEINFO_PERJIEXU   328
#define IDC_EDIT_DTCABLEINFO_PERRENFM   329
#define IDC_EDIT_DTCABLEINFO_PERSXJ     330
#define IDC_EDIT_DLPX_SAVEPATH          1000
#define IDC_BUTTON_DLPX_SELPATH         1001
#define IDC_COMBO_MODE                  1005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         303
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
